substitutions:
  friendly_name: Arc Lamp
  hostname: arc_lamp
  light_name: Arc Lamp

packages:
  base: !include device/arlec_GLD122HA.yaml
 
# esphome:
#   on_boot:
#     priority: 300
#     then:
#       - light.turn_on:
#           id: bulb
#           transition_length: 0s
#           brightness: 60%
#           color_temperature: 357 mireds