substitutions:
  friendly_name: Bedside Lamp
  hostname: bedside_lamp
  light_name: Jonas Bedside
  platform: ESP8266
  board: esp01_1m

packages:
  base: !include device/generic.yaml

logger:
  # Disable logging to serial
  baud_rate: 0

output:
  - platform: esp8266_pwm
    id: light_pwm
    pin: GPIO14

light:
  - platform: monochromatic
    name: "${light_name}"
    output: light_pwm
