substitutions:
  name: Bedside Lamp
  id: bedside_lamp
  platform: ESP8266
  board: esp01_1m

packages:
  base: !include defaults.yml

logger:
  # Disable logging to serial
  baud_rate: 0

output:
  - platform: esp8266_pwm
    id: light_pwm
    pin: GPIO14

light:
  - platform: monochromatic
    name: "Bulb"
    output: light_pwm
