esphome:
  name: bedside_lamp
  platform: ESP8266
  board: esp01_1m
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

# Enable logging
logger:
  # Disable logging to serial
  baud_rate: 0

# Enable Home Assistant API
api:
  password: !secret api_password

ota:

output:
  - platform: esp8266_pwm
    id: light_pwm
    pin: GPIO14

light:
  - platform: monochromatic
    name: "Bulb"
    output: light_pwm