esphome:
  name: ${id}
  platform: ${platform}
  board: ${board}
  build_path: ./.build/${name}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: false
  use_address: ${id}.our.lemon.nz

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password
  reboot_timeout: 1h

ota:

time:
  - platform: homeassistant

sun:
  latitude: !secret lat
  longitude: !secret lng

sensor:
  - platform: uptime
    name: ${name} Device Uptime
  - platform: wifi_signal
    name: ${name} WiFi Signal
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${name} WiFi IP
    ssid:
      name: ${name} WiFi SSID
    bssid:
      name: ${name} WiFi BSSID
    mac_address:
      name: ${name} WiFi MAC
