substitutions:
  name: garage_light
  platform: ESP8266
  board: esp01_1m

<<: !include defaults.yml

logger:
  # Disable logging to serial
  baud_rate: 0

output:
  - platform: esp8266_pwm
    id: light_pwm
    pin: GPIO05

light:
  - platform: monochromatic
    name: "Bulb"
    output: light_pwm
    restore_mode: ALWAYS_ON
