substitutions:
  friendly_name: Greenhouse Controller
  hostname: greenhouse_controller
  channel_a: Greenhouse Lights
  channel_b: Greenhouse Humidifier
  channel_c: Greenhouse Fountain
  channel_d: TBD

packages:
  base: !include device/esp12f_relay_x4.yaml

dallas:
  - pin: GPIO5
    update_interval: 20s

sensor:
  - platform: dallas
    id: temp_probe
    address: 0xD903079779B94528
    name: Greenhouse Temperature
  #- platform: dht
  #  pin: GPIO5
  #  model: AM2302
  #  temperature:
  #    name: Greenhouse Temperature
  #    id: dht_temp
  #  humidity:
  #    name: Greenhouse Humidity
  #    id: dht_humidity
  #  update_interval: 20s
