substitutions:
  friendly_name: Greenhouse Controller
  hostname: greenhouse_controller
  channel_a: Greenhouse Fountain
  channel_b: TBD
  channel_c: Greenhouse Lights
  channel_d: Greenhouse Fan

packages:
  base: !include device/esp12f_relay_x4.yaml

dallas:
  - pin: GPIO5
    update_interval: 20s

sensor:
  - platform: dallas
    id: temp_probe
    address: 0xD903079779B94528
    name: Greenhouse Temperature
  - platform: dht
    pin: GPIO4
    temperature:
      name: Greenhouse Temperature (DHT)
      id: dht_temp
    humidity:
      name: Greenhouse Humidity
      id: dht_humidity
    update_interval: 20s
