substitutions:
  friendly_name: Greenhouse Controller TEST
  hostname: greenhouse_controller_test
  channel_a: Chan 1
  channel_b: Chan 2
  channel_c: Chan 3
  channel_d: Chan 4

packages:
  base: !include device/esp12f_relay_x4.yaml
