substitutions:
  friendly_name: spa test
  hostname: spa_test

esphome:
  name: ${hostname}
  build_path: ./build/${hostname}
  platformio_options:
    # upload_speed: 115200
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    version: latest
    sdkconfig_options:
      #CONFIG_ESP_CONSOLE_USB_CDC: y
      CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG: y

external_components:
  - source: github://pr#3105
    components: [ logger ]

logger:
  level: VERY_VERBOSE
  hardware_uart: STDOUT

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: false
  reboot_timeout: 300s
  domain: !secret wifi_domain

api:
  reboot_timeout: 30min
  password: !secret api_password

ota:

time:
  - platform: homeassistant

sun:
  latitude: !secret lat
  longitude: !secret lng

packages:
  status: !include ./common/status.yaml
