esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf

packages:
  base: !include ../common/base.yaml
  status: !include ../common/status.yaml

logger:
  level: DEBUG
  baud_rate: 0

wifi: !remove
sensor:
  - id: !remove device_wifi_signal

text_sensor:
  - id: !remove wifi_info

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    mode: CLK_OUT
    pin: 17
  phy_addr: 0
  power_pin: GPIO12
  # domain: !secret wifi_domain


