substitutions:
  platform: ESP8266
  board: esp01_1m

packages:
  base: !include ../common/base.yaml
  status: !include ../common/status.yaml

status_led:
  pin: GPIO0

output:
  - platform: gpio
    pin: GPIO15
    id: relay

light:
  - platform: binary
    name: "${light_name}"
    id: bulb
    output: relay

sensor:
  - platform: hlw8012
    cf_pin: GPIO05
    cf1_pin: GPIO13 # not used because it is not available on the 1PM but it is needed to compile
    sel_pin: GPIO14 # not used because it is not available on the 1PM but it is needed to compile
    power:
      name: "${friendly_name} Power"
      unit_of_measurement: W
      id: "${hostname}_power"
      icon: mdi:flash-circle
      accuracy_decimals: 0
      filters:
      #Reading -> actual#
      - calibrate_linear:
          - 2.5 -> 0.16
          - 747.0 -> 125.0
          - 1409.0 -> 237.0
          - 2663.0 -> 444.0
          - 8600.0 -> 1390.0
      - lambda: if (x <= 6.0) return 0; else return (x - 6);
    update_interval: 10s
    
  # NTC Temperature
  - platform: ntc
    sensor: ${hostname}_resistance_sensor
    name: "${friendly_name} Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
  - platform: resistance
    id: ${hostname}_resistance_sensor
    sensor: ${hostname}_source_sensor
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: ${hostname}_source_sensor
    pin: A0
    update_interval: 10s

binary_sensor:
  # Binary sensor for the button press
  - platform: gpio
    name: "${friendly_name} Input"
    pin:
      number: GPIO4
    on_state:
      - light.toggle: bulb