substitutions:
  platform: ESP8266
  board: esp01_1m

packages:
  base: !include ../common/base.yaml
  status: !include ../common/status.yaml

i2c:
  sda: GPIO12
  scl: GPIO14

sensor:
  - platform: ade7953
    voltage:
      name: ${friendly_name} Voltage
    current_a:
      name: ${channel_b} Current
    current_b:
      name: ${channel_a} Current
    active_power_a:
      name: ${channel_b} Power
      filters:
        - multiply: -1
    active_power_b:
      name: ${channel_a} Power
      filters:
        - multiply: -1
    update_interval: 15s

  # NTC Temperature
  - platform: ntc
    sensor: temp_resistance_reading
    name: ${friendly_name} Temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: temp_analog_reading
    pin: A0

status_led:
  pin:
    number: GPIO0
    inverted: yes

binary_sensor:
  - platform: gpio
    pin: GPIO16
    name: "ade7953 IRQ pin"
    internal: true
  - platform: gpio
    pin:
      number: GPIO13
    name: "${channel_a} Switch"
    on_press:
      then:
        - switch.toggle: shelly_relay_a
  - platform: gpio
    pin:
      number: GPIO5
    name: "${channel_b} Switch"
    on_press:
      then:
        - switch.toggle: shelly_relay_b

switch:
  - platform: gpio
    id: shelly_relay_a
    name: "${channel_a} Relay"
    pin: GPIO15
    icon: "mdi:electric-switch"
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    id: shelly_relay_b
    name: "${channel_b} Relay"
    pin: GPIO4
    icon: "mdi:electric-switch"
    restore_mode: RESTORE_DEFAULT_OFF
